//
//  QuestionBank.swift
//  Table Of Squares
//
//  Created by Daniel Khromov on 12/05/2019.
//  Copyright © 2019 Daniel Khromov. All rights reserved.
//

import Foundation

class QuestionBank {
    var list = [Question]()
    
    init() {
        // Creating a quiz item and appending it to the list
        let item = Question(text: "2² = ", correctAnswer: "4")
        
        list.append(item)
        
        list.append(Question(text: "3² = ", correctAnswer: "9"))
        list.append(Question(text: "4² = ", correctAnswer: "16"))
        list.append(Question(text: "5² = ", correctAnswer: "25"))
        list.append(Question(text: "6² = ", correctAnswer: "36"))
        list.append(Question(text: "7² = ", correctAnswer: "49"))
        list.append(Question(text: "8² = ", correctAnswer: "64"))
        list.append(Question(text: "9² = ", correctAnswer: "81"))
        list.append(Question(text: "10² = ", correctAnswer: "100"))
        list.append(Question(text: "11² = ", correctAnswer: "121"))
        list.append(Question(text: "12² = ", correctAnswer: "144"))
        list.append(Question(text: "13² = ", correctAnswer: "169"))
        list.append(Question(text: "14² = ", correctAnswer: "196"))
        list.append(Question(text: "15² = ", correctAnswer: "225"))
        list.append(Question(text: "16² = ", correctAnswer: "256"))
        list.append(Question(text: "17² = ", correctAnswer: "289"))
        list.append(Question(text: "18² = ", correctAnswer: "324"))
        list.append(Question(text: "19² = ", correctAnswer: "361"))
        list.append(Question(text: "20² = ", correctAnswer: "400"))
        list.append(Question(text: "21² = ", correctAnswer: "441"))
        list.append(Question(text: "22² = ", correctAnswer: "484"))
        list.append(Question(text: "23² = ", correctAnswer: "529"))
        list.append(Question(text: "24² = ", correctAnswer: "576"))
        list.append(Question(text: "25² = ", correctAnswer: "625"))
        list.append(Question(text: "26² = ", correctAnswer: "676"))
        list.append(Question(text: "27² = ", correctAnswer: "729"))
        list.append(Question(text: "28² = ", correctAnswer: "784"))
        list.append(Question(text: "29² = ", correctAnswer: "841"))
        list.append(Question(text: "30² = ", correctAnswer: "900"))
        list.append(Question(text: "3² = ", correctAnswer: "9"))
        list.append(Question(text: "4² = ", correctAnswer: "16"))
        list.append(Question(text: "5² = ", correctAnswer: "25"))
        list.append(Question(text: "6² = ", correctAnswer: "36"))
        list.append(Question(text: "7² = ", correctAnswer: "49"))
        list.append(Question(text: "8² = ", correctAnswer: "64"))
        list.append(Question(text: "9² = ", correctAnswer: "81"))
        list.append(Question(text: "10² = ", correctAnswer: "100"))
        list.append(Question(text: "11² = ", correctAnswer: "121"))
        list.append(Question(text: "12² = ", correctAnswer: "144"))
        list.append(Question(text: "13² = ", correctAnswer: "169"))
        list.append(Question(text: "14² = ", correctAnswer: "196"))
        list.append(Question(text: "15² = ", correctAnswer: "225"))
        list.append(Question(text: "16² = ", correctAnswer: "256"))
        list.append(Question(text: "17² = ", correctAnswer: "289"))
        list.append(Question(text: "18² = ", correctAnswer: "324"))
        list.append(Question(text: "19² = ", correctAnswer: "361"))
        list.append(Question(text: "20² = ", correctAnswer: "400"))
        list.append(Question(text: "21² = ", correctAnswer: "441"))
        list.append(Question(text: "22² = ", correctAnswer: "484"))
        list.append(Question(text: "23² = ", correctAnswer: "529"))
        list.append(Question(text: "24² = ", correctAnswer: "576"))
        list.append(Question(text: "25² = ", correctAnswer: "625"))
        list.append(Question(text: "26² = ", correctAnswer: "676"))
        list.append(Question(text: "27² = ", correctAnswer: "729"))
        list.append(Question(text: "28² = ", correctAnswer: "784"))
        list.append(Question(text: "29² = ", correctAnswer: "841"))
        list.append(Question(text: "30² = ", correctAnswer: "900"))
        list.append(Question(text: "3² = ", correctAnswer: "9"))
        list.append(Question(text: "4² = ", correctAnswer: "16"))
        list.append(Question(text: "5² = ", correctAnswer: "25"))
        list.append(Question(text: "6² = ", correctAnswer: "36"))
        list.append(Question(text: "7² = ", correctAnswer: "49"))
        list.append(Question(text: "8² = ", correctAnswer: "64"))
        list.append(Question(text: "9² = ", correctAnswer: "81"))
        list.append(Question(text: "10² = ", correctAnswer: "100"))
        list.append(Question(text: "11² = ", correctAnswer: "121"))
        list.append(Question(text: "12² = ", correctAnswer: "144"))
        list.append(Question(text: "13² = ", correctAnswer: "169"))
        list.append(Question(text: "14² = ", correctAnswer: "196"))
        list.append(Question(text: "15² = ", correctAnswer: "225"))
        list.append(Question(text: "16² = ", correctAnswer: "256"))
        list.append(Question(text: "17² = ", correctAnswer: "289"))
        list.append(Question(text: "18² = ", correctAnswer: "324"))
        list.append(Question(text: "19² = ", correctAnswer: "361"))
        list.append(Question(text: "20² = ", correctAnswer: "400"))
        list.append(Question(text: "21² = ", correctAnswer: "441"))
        list.append(Question(text: "22² = ", correctAnswer: "484"))
        list.append(Question(text: "23² = ", correctAnswer: "529"))
        list.append(Question(text: "24² = ", correctAnswer: "576"))
        list.append(Question(text: "25² = ", correctAnswer: "625"))
        list.append(Question(text: "26² = ", correctAnswer: "676"))
        list.append(Question(text: "27² = ", correctAnswer: "729"))
        list.append(Question(text: "28² = ", correctAnswer: "784"))
        list.append(Question(text: "29² = ", correctAnswer: "841"))
        list.append(Question(text: "30² = ", correctAnswer: "900"))
        list.append(Question(text: "3² = ", correctAnswer: "9"))
        list.append(Question(text: "4² = ", correctAnswer: "16"))
        list.append(Question(text: "5² = ", correctAnswer: "25"))
        list.append(Question(text: "6² = ", correctAnswer: "36"))
        list.append(Question(text: "7² = ", correctAnswer: "49"))
        list.append(Question(text: "8² = ", correctAnswer: "64"))
        list.append(Question(text: "9² = ", correctAnswer: "81"))
        list.append(Question(text: "10² = ", correctAnswer: "100"))
        list.append(Question(text: "11² = ", correctAnswer: "121"))
        list.append(Question(text: "12² = ", correctAnswer: "144"))
        list.append(Question(text: "13² = ", correctAnswer: "169"))
        list.append(Question(text: "14² = ", correctAnswer: "196"))
        list.append(Question(text: "15² = ", correctAnswer: "225"))
        list.append(Question(text: "16² = ", correctAnswer: "256"))
        list.append(Question(text: "17² = ", correctAnswer: "289"))
        list.append(Question(text: "18² = ", correctAnswer: "324"))
        list.append(Question(text: "19² = ", correctAnswer: "361"))
        list.append(Question(text: "20² = ", correctAnswer: "400"))
        list.append(Question(text: "21² = ", correctAnswer: "441"))
        list.append(Question(text: "22² = ", correctAnswer: "484"))
        list.append(Question(text: "23² = ", correctAnswer: "529"))
        list.append(Question(text: "24² = ", correctAnswer: "576"))
        list.append(Question(text: "25² = ", correctAnswer: "625"))
        list.append(Question(text: "26² = ", correctAnswer: "676"))
        list.append(Question(text: "27² = ", correctAnswer: "729"))
        list.append(Question(text: "28² = ", correctAnswer: "784"))
        list.append(Question(text: "29² = ", correctAnswer: "841"))
        list.append(Question(text: "30² = ", correctAnswer: "900"))
        list.append(Question(text: "3² = ", correctAnswer: "9"))
        list.append(Question(text: "4² = ", correctAnswer: "16"))
        list.append(Question(text: "5² = ", correctAnswer: "25"))
        list.append(Question(text: "6² = ", correctAnswer: "36"))
        list.append(Question(text: "7² = ", correctAnswer: "49"))
        list.append(Question(text: "8² = ", correctAnswer: "64"))
        list.append(Question(text: "9² = ", correctAnswer: "81"))
        list.append(Question(text: "10² = ", correctAnswer: "100"))
        list.append(Question(text: "11² = ", correctAnswer: "121"))
        list.append(Question(text: "12² = ", correctAnswer: "144"))
        list.append(Question(text: "13² = ", correctAnswer: "169"))
        list.append(Question(text: "14² = ", correctAnswer: "196"))
        list.append(Question(text: "15² = ", correctAnswer: "225"))
        list.append(Question(text: "16² = ", correctAnswer: "256"))
        list.append(Question(text: "17² = ", correctAnswer: "289"))
        list.append(Question(text: "18² = ", correctAnswer: "324"))
        list.append(Question(text: "19² = ", correctAnswer: "361"))
        list.append(Question(text: "20² = ", correctAnswer: "400"))
        list.append(Question(text: "21² = ", correctAnswer: "441"))
        list.append(Question(text: "22² = ", correctAnswer: "484"))
        list.append(Question(text: "23² = ", correctAnswer: "529"))
        list.append(Question(text: "24² = ", correctAnswer: "576"))
        list.append(Question(text: "25² = ", correctAnswer: "625"))
        list.append(Question(text: "26² = ", correctAnswer: "676"))
        list.append(Question(text: "27² = ", correctAnswer: "729"))
        list.append(Question(text: "28² = ", correctAnswer: "784"))
        list.append(Question(text: "29² = ", correctAnswer: "841"))
        list.append(Question(text: "30² = ", correctAnswer: "900"))
        list.append(Question(text: "3² = ", correctAnswer: "9"))
        list.append(Question(text: "4² = ", correctAnswer: "16"))
        list.append(Question(text: "5² = ", correctAnswer: "25"))
        list.append(Question(text: "6² = ", correctAnswer: "36"))
        list.append(Question(text: "7² = ", correctAnswer: "49"))
        list.append(Question(text: "8² = ", correctAnswer: "64"))
        list.append(Question(text: "9² = ", correctAnswer: "81"))
        list.append(Question(text: "10² = ", correctAnswer: "100"))
        list.append(Question(text: "11² = ", correctAnswer: "121"))
        list.append(Question(text: "12² = ", correctAnswer: "144"))
        list.append(Question(text: "13² = ", correctAnswer: "169"))
        list.append(Question(text: "14² = ", correctAnswer: "196"))
        list.append(Question(text: "15² = ", correctAnswer: "225"))
        list.append(Question(text: "16² = ", correctAnswer: "256"))
        list.append(Question(text: "17² = ", correctAnswer: "289"))
        list.append(Question(text: "18² = ", correctAnswer: "324"))
        list.append(Question(text: "19² = ", correctAnswer: "361"))
        list.append(Question(text: "20² = ", correctAnswer: "400"))
        list.append(Question(text: "21² = ", correctAnswer: "441"))
        list.append(Question(text: "22² = ", correctAnswer: "484"))
        list.append(Question(text: "23² = ", correctAnswer: "529"))
        list.append(Question(text: "24² = ", correctAnswer: "576"))
        list.append(Question(text: "25² = ", correctAnswer: "625"))
        list.append(Question(text: "26² = ", correctAnswer: "676"))
        list.append(Question(text: "27² = ", correctAnswer: "729"))
        list.append(Question(text: "28² = ", correctAnswer: "784"))
        list.append(Question(text: "29² = ", correctAnswer: "841"))
        list.append(Question(text: "30² = ", correctAnswer: "900"))
}
}
